import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useFamily } from "./useFamily";
import { useToast } from "./use-toast";
import { Recipe, Ingredient } from "./useRecipes";
import { startOfWeek, addDays } from "date-fns";

export interface Meal {
    id: string;
    type: "breakfast" | "lunch" | "dinner";
    name: string;
    recipeId?: string; // Link to a recipe
    ingredients?: Ingredient[]; // For custom meals
    notes?: string;
}

export interface DayPlan {
    date: string;
    dayName: string; // Segunda, Terça...
    shortName: string; // Seg, Ter...
    meals: Meal[];
}

const dayNames = ["Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado"];
const shortNames = ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"];

const generateWeekForDate = (referenceDate: Date): DayPlan[] => {
    const start = startOfWeek(referenceDate, { weekStartsOn: 0 }); // Sunday start

    return Array.from({ length: 7 }, (_, i) => {
        const date = addDays(start, i);
        const dayName = dayNames[date.getDay()];
        const shortName = shortNames[date.getDay()];
        return {
            date: date.toISOString().split("T")[0], // YYYY-MM-DD
            dayName,
            dayName,
            shortName,
            meals: [],
        };
    });
};

export function useMealPlan(referenceDate: Date = new Date()) {
    const { toast } = useToast();
    const { family } = useFamily();
    const [weekPlan, setWeekPlan] = useState<DayPlan[]>(() => generateWeekForDate(referenceDate));
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        setWeekPlan(generateWeekForDate(referenceDate));
    }, [referenceDate]);

    useEffect(() => {
        if (family?.id) {
            fetchWeeklyPlan();
        } else {
            // Keep the empty structure generated by referenceDate
            setLoading(false);
        }
    }, [family?.id, weekPlan[0].date]); // Refetch when family or week changes

    const fetchWeeklyPlan = async () => {
        if (!family?.id) return;
        try {
            // Fetch plans for the range dates in weekPlan
            const startStr = weekPlan[0].date;
            const endStr = weekPlan[6].date;

            const { data, error } = await supabase
                .from('meal_plans')
                .select('*')
                .eq('family_id', family.id)
                .gte('date', startStr)
                .lte('date', endStr);

            if (error) throw error;

            // Merge DB data into weekPlan structure
            setWeekPlan(prev => prev.map(day => {
                const dbRecord = data.find(r => r.date === day.date);
                if (dbRecord && dbRecord.meals) {
                    const meals = Array.isArray(dbRecord.meals) ? (dbRecord.meals as unknown as Meal[]) : [];
                    return { ...day, meals };
                }
                return { ...day, meals: [] }; // Clear meals if no record found (important when switching weeks)
            }));

        } catch (error) {
            console.error("Error fetching meal plans:", error);
        } finally {
            setLoading(false);
        }
    };

    const addMeal = async (date: string, meal: Meal) => {
        if (!family?.id) return;

        // Optimistic update
        const previousPlan = [...weekPlan];

        // Find current day's meals
        // Check if the date is within the current view
        const dayIndex = weekPlan.findIndex(d => d.date === date);

        if (dayIndex !== -1) {
            const dayPlan = weekPlan[dayIndex];
            const filteredMeals = dayPlan.meals.filter(m => m.type !== meal.type); // Replace existing meal of same type
            const newMeals = [...filteredMeals, meal];

            setWeekPlan((prev) => {
                const newPlan = [...prev];
                newPlan[dayIndex] = { ...dayPlan, meals: newMeals };
                return newPlan;
            });

            // Sync to DB (Upsert)
            try {
                const { error } = await supabase
                    .from('meal_plans')
                    .upsert({
                        family_id: family.id,
                        date: date,
                        meals: newMeals as unknown as any // Cast for Json compatibility
                    }, { onConflict: 'family_id,date' });

                if (error) throw error;

                toast({
                    title: "🍽️ Refeição planejada!",
                    description: meal.name,
                });

            } catch (error) {
                console.error("Error saving meal:", error);
                toast({ title: "Erro ao salvar", variant: "destructive" });
                setWeekPlan(previousPlan);
            }
        } else {
            // Saving for a date not currently in view? Just allow it to save to DB.
            // But usually UI restricts add to current view.
            try {
                // Fetch existing meals for that day from DB first? 
                // For now, simplicity: we assume we only edit what we see.
                // If adding to a date outside view, we would need to fetch that day first to append.
                // But in our UI we select "Add Meal" on a specific day in view.
                console.warn("Attempting to add meal to date outside current view");
            } catch (e) { }
        }
    };

    const removeMeal = async (date: string, mealId: string) => {
        if (!family?.id) return;

        const dayIndex = weekPlan.findIndex(d => d.date === date);
        if (dayIndex === -1) return;

        const dayPlan = weekPlan[dayIndex];
        const newMeals = dayPlan.meals.filter(m => m.id !== mealId);

        setWeekPlan((prev) => {
            const newPlan = [...prev];
            newPlan[dayIndex] = { ...dayPlan, meals: newMeals };
            return newPlan;
        });

        toast({
            title: "Refeição removida",
        });

        // Sync to DB
        try {
            const { error } = await supabase
                .from('meal_plans')
                .upsert({
                    family_id: family.id,
                    date: date,
                    meals: newMeals as unknown as any // Cast for Json compatibility
                }, { onConflict: 'family_id,date' });

            if (error) throw error;
        } catch (error) {
            console.error("Error removing meal:", error);
            toast({ title: "Erro ao salvar", variant: "destructive" });
        }
    };

    return {
        weekPlan,
        addMeal,
        removeMeal,
        loading
    };
}
